local mark = require("harpoon.mark")
local ui = require("harpoon.ui")

vim.keymap.set("n", "<C-h>", function() ui.nav_file(1) end)
vim.keymap.set("n", "<C-t>", function() ui.nav_file(2) end)
vim.keymap.set("n", "<C-n>", function() ui.nav_file(3) end)
vim.keymap.set("n", "<C-s>", function() ui.nav_file(4) end)
vim.keymap.set("n", "<leader>g", function() ui.toggle_quick_menu() end, opts)
vim.keymap.set("n", "<leader>m", function() mark.add_file() end, opts)
vim.keymap.set("n", "<leader>m", ":lua require('harpoon.mark').add_file()<CR>", opts)
